apiVersion: v1
kind: ConfigMap
metadata:
  name: indexer-config
  namespace: wazuh-security
data:
  opensearch.yml: |
    network.host: "0.0.0.0"
    node.name: "${HOSTNAME}"
    cluster.initial_master_nodes:
      - "wazuh-indexer-0"
    cluster.name: "wazuh-cluster"
    discovery.seed_hosts:
      - "wazuh-indexer-0.wazuh-indexer.wazuh-security.svc.cluster.local"

    # Compatibility setting for Filebeat 7.10.2 _type parameter
    compatibility.override_main_response_version: true

    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/certs/node.pem
    plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/certs/node-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem

    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/certs/node.pem
    plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/certs/node-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false

    plugins.security.nodes_dn:
      - "CN=wazuh-indexer,O=Cortex,ST=CA,C=US"
      - "CN=admin,O=Cortex,ST=CA,C=US"
      - "CN=filebeat,O=Cortex,ST=CA,C=US"

    plugins.security.authcz.admin_dn:
      - "CN=admin,O=Cortex,ST=CA,C=US"

    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
