---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cortex
spec:
  tls:
  - hosts:
    - cortex.production.example.com
    secretName: cortex-prod-tls
  rules:
  - host: cortex.production.example.com
