apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sms-relay
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: sms.ry-ops.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sms-relay
            port:
              number: 80
